config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "users/registrations"}
  resources :shop_item_images
  root :to => "shop_items#index"
  resources :shop_items do 
    member do 
      get "search" 
    end
  end 

  post '/buckets', to: 'buckets#realize_payments'
  resources :bucket_items, only: [:create,:destroy]
  resources :user, only: [:show]
  resources :comments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/shop_item.rb
class ShopItem < ApplicationRecord
    has_many :shop_item_images, dependent: :destroy
    belongs_to :user
    accepts_nested_attributes_for :shop_item_images 
    validates :title, presence:true 
    validates :category, presence:true
    validates :description, presence:true
    validates :amount, presence:true
    validates :price, presence:true
    scope :choosen_category, -> (choosen_category) {where category: choosen_category}
    scope :choosen_min_price, -> (choosen_min_price) {where("price > ?",choosen_min_price)}
    scope :choosen_max_price, -> (choosen_max_price) {where("price < ?",choosen_max_price)}
end 

app/controllers/shop_items_controller.rb
class ShopItemsController < ApplicationController
    before_action :authenticate_user!
    def new
        @shop_item = current_user.shop_items.new 
        @shop_item_image = @shop_item.shop_item_images.build 
    end
    def search
        respond_data = ShopItem.where(nil)
        puts filtering_params
        filtering_params.each do |key,value|
            respond_data = respond_data.public_send(key, value) if value.present?
        end
        respond_to do |format|
            format.html { render :json => respond_data.to_json(:include => [:shop_item_images])}
        end
    end 
    def create
        @shop_item = current_user.shop_items.new(item_params)

        if @shop_item.save
            
            if !params[:shop_item][:shop_item_image].blank?

                params[:shop_item][:shop_item_image][:picture_path].each do |a|
                    @shop_item_image = @shop_item.shop_item_images.create!(:picture_path => a, :shop_item_id => @shop_item.id)
                end
            end
            redirect_to shop_item_path(@shop_item.id)
        end 
    end

    def show 
        @shop_item = current_user.shop_items.find(params[:id])
        @shop_item_images = @shop_item.shop_item_images.all
    end 
    def edit
        @shop_item = current_user.shop_items.find(params[:id ])
    end 

    def update 
        @shop_item = current_user.shop_items.find(params[:id])
        @shop_item.update(item_params)
        puts params[:shop_item][:shop_item_image]
        if params[:delete].present?
            params[:delete].each do |p|

               current_user.shop_items.shop_item_images.find(p[0]).destroy
            end 
        end 
        if !params[:shop_item][:shop_item_image].blank?
            params[:shop_item][:shop_item_image][:picture_path].each do |a|
                @shop_item_image = @shop_item.shop_item_images.create!(:picture_path => a, :shop_item_id => @shop_item.id)
            end
        end
        redirect_to shop_item_path(@shop_item)
        
    end 

    def destroy 
        @shop_item = current_user.shop_items.find(params[:id])

        @shop_item.destroy 

        redirect_to root_path
    end 

    def index
        #@shop_items = current_user.shop_items.all 
        @shop_items = ShopItem.all

        respond_to do |format|
            format.html
            format.json { render :json => @shop_items.to_json(:include => [:shop_item_images]) }
        end  
    end

    private 
    def item_params
        params.require(:shop_item).permit(:price,:description,:title,:category,:amount)
    end

    def filtering_params
        params[:shop_item_data].slice(:choosen_category,:choosen_min_price,:choosen_max_price)
    end 
end

app/helpers/shop_items_helper.rb
module ShopItemsHelper
end

app/views/shop_items/edit.haml
.card.shop_item_form
    .card-header
        Edit
    .card-block
        = simple_form_for @shop_item do |f|
            = f.input :price 
            = f.input :description
            = f.input :title  
            = f.input :amount
            - @shop_item.shop_item_images.each do |p|
                %img{:src => p.picture_path, :style => "width:40px"}
                = check_box_tag("delete[#{p.id}]")
            = f.fields_for :shop_item_image do |p|
                = p.file_field :picture_path, :multiple => true
        
            = f.submit

app/views/shop_items/index.haml
.main-content

    %h2 Hello all shopitems 

    - if flash[:bucket_item_info]
        .alert.alert-success
            = flash[:bucket_item_info]
    %form{:action => "/",:id=>"searchForm"}
        %select.category
            %option{:value => "car"} Car
            %option{:value => "motorcycle"} Motorcycle
            %option{:value => "bike"} Bike

        %input.minPrice{:placeholder => "Enter min shop_item price", :style =>"display:block;"}
        %input.maxPrice{:placeholder => "Enter max shop_item price", :style =>"display:block;"}

        %input{:type => "submit", :value => "Search"}
    .card.bucket 
        .card-header
            %a{:data => {:toggle => "collapse"},:href=>"#collapse-example",:aria => {:expanded => "true", :controls => "collapse-example", :id => "heading-example",:class => "d-block"}} Your shopping card
        #collapse-example.collapse.show{:aria => {:labelledby => "heading-example"}}
            .card-body
                = current_user.bucket.pay_amount 
                $ to pay
                - current_user.bucket.bucket_items.each do |bucket_item|
                    .bucket_item_holder
                        %p{:style => "color:black;display: inline-block"}
                            = bucket_item.title 
                        .btn.btn-success.remove_from_bucket{:style => "margin-bottom:5px;",:data => {:id => bucket_item.id}}-
                .btn.btn-success#pay Pay
    .container
        - @shop_items.each_slice(3) do |shop_item_for_row|
            .row.shop_items_holder
                - shop_item_for_row.each do |shop_item|
                    .col-3.shop_item_holder  
                        %h2
                            = link_to shop_item.title, shop_item_path(shop_item)
                        - unless shop_item.shop_item_images.first.nil?
                            %p
                                %img{:src => shop_item.shop_item_images.first.picture_path,:style => "width:80px"}
                        %p 
                            = shop_item.description
                        %p
                            = shop_item.price  
                            $
                        .btn.btn-success.add_to_bucket{:style => "margin-bottom:5px;",:data => {:id => shop_item.id}}+ 
    //= react_component('AllItems')
    = link_to "Add shop item", new_shop_item_path(), class: "btn btn-primary"
    

app/views/shop_items/new.haml
.card.shop_item_form
    .card-header
        New Shop Item
    .card-block
        = simple_form_for @shop_item do |f|
            = f.input :price 
            = f.input :description
            = f.input :title  
            = f.input :amount
            = f.input :category, collection: [:car,:motorcycle,:bike]
            = f.fields_for :shop_item_image do |p|
                = p.file_field :picture_path, :multiple => true
        
            = f.submit

//name: "shop_item_image[picture_path][]"

app/views/shop_items/show.haml
.wrapper
    .main-content.active
        %h2
            = @shop_item.title
        %h4
            = @shop_item.description
        %p 
            = @shop_item.price
        %p 
            = @shop_item.amount
        %p 
            = link_to @shop_item.user.email, user_path(@shop_item.user.id), :style => "color:black"

        - if @shop_item.shop_item_images.length == 1
            %img{:src => @shop_item.shop_item_images[0].picture_path, :style => "width:400px", class:"image"}
        -else
            %div{id:"carouselExample", class:"carousel slide", :data => {:ride=>"carousel"}}
                .carousel-inner
                    - @shop_item.shop_item_images.each_with_index do |shop_item_image,index|
                        - if index == 0
                            .carousel-item.active 
                                %img{:src => shop_item_image.picture_path,  class:"d-block w-50", alt:"pic-#{shop_item_image.id}"}
                        - else 
                            .carousel-item
                                %img{:src => shop_item_image.picture_path,  class:"d-block w-50", alt:"pic-#{shop_item_image.id}"}

        .buttons2    
            = link_to "Edit" , edit_shop_item_path(@shop_item),class: "btn btn-primary"
            = link_to "Delete", @shop_item, method: "delete", data: {confirm: "Are you sure?"}, class: "btn btn-success"