config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "users/registrations"}
  resources :shop_item_images
  root :to => "shop_items#index"
  resources :shop_items do 
    member do 
      get "search" 
    end
  end 

  post '/buckets', to: 'buckets#realize_payments'
  resources :bucket_items, only: [:create,:destroy]
  resources :user, only: [:show]
  resources :comments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/shop_item_image.rb
class ShopItemImage < ApplicationRecord
    mount_uploader :picture_path, ShopPictureUploader
    belongs_to :shop_item
end

app/controllers/shop_item_images_controller.rb
class ShopItemImagesController < ApplicationController
  before_action :set_shop_item_image, only: [:show, :edit, :update, :destroy]

  # GET /shop_item_images
  # GET /shop_item_images.json
  def index
    @shop_item_images = ShopItemImage.all
  end

 
  # GET /shop_item_images/1
  # GET /shop_item_images/1.json
  def show
  end

  # GET /shop_item_images/new
  def new
    @shop_item_image = ShopItemImage.new
  end

  # GET /shop_item_images/1/edit
  def edit
  end

  # POST /shop_item_images
  # POST /shop_item_images.json
  def create
    @shop_item_image = ShopItemImage.new(shop_item_image_params)

    respond_to do |format|
      if @shop_item_image.save
        format.html { redirect_to @shop_item_image, notice: 'Shop item image was successfully created.' }
        format.json { render :show, status: :created, location: @shop_item_image }
      else
        format.html { render :new }
        format.json { render json: @shop_item_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shop_item_images/1
  # PATCH/PUT /shop_item_images/1.json
  def update
    respond_to do |format|
      if @shop_item_image.update(shop_item_image_params)
        format.html { redirect_to @shop_item_image, notice: 'Shop item image was successfully updated.' }
        format.json { render :show, status: :ok, location: @shop_item_image }
      else
        format.html { render :edit }
        format.json { render json: @shop_item_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shop_item_images/1
  # DELETE /shop_item_images/1.json
  def destroy
    @shop_item_image.destroy
    respond_to do |format|
      format.html { redirect_to shop_item_images_url, notice: 'Shop item image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop_item_image
      @shop_item_image = ShopItemImage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shop_item_image_params
      params.require(:shop_item_image).permit(:shop_item_id, :picture_path)
    end
end

app/helpers/shop_item_images_helper.rb
module ShopItemImagesHelper
end

app/views/shop_item_images/_form.html.erb
<%= form_with(model: shop_item_image, local: true) do |form| %>
  <% if shop_item_image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shop_item_image.errors.count, "error") %> prohibited this shop_item_image from being saved:</h2>

      <ul>
      <% shop_item_image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :shop_item_id %>
    <%= form.number_field :shop_item_id %>
  </div>

  <div class="field">
    <%= form.label :picture_path %>
    <%= form.text_field :picture_path %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shop_item_images/edit.html.erb
<h1>Editing Shop Item Image</h1>

<%= render 'form', shop_item_image: @shop_item_image %>

<%= link_to 'Show', @shop_item_image %> |
<%= link_to 'Back', shop_item_images_path %>

app/views/shop_item_images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shop Item Images</h1>

<table>
  <thead>
    <tr>
      <th>Shop item</th>
      <th>Picture path</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shop_item_images.each do |shop_item_image| %>
      <tr>
        <td><%= shop_item_image.shop_item_id %></td>
        <td><%= shop_item_image.picture_path %></td>
        <td><%= link_to 'Show', shop_item_image %></td>
        <td><%= link_to 'Edit', edit_shop_item_image_path(shop_item_image) %></td>
        <td><%= link_to 'Destroy', shop_item_image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shop Item Image', new_shop_item_image_path %>

app/views/shop_item_images/new.html.erb
<h1>New Shop Item Image</h1>

<%= render 'form', shop_item_image: @shop_item_image %>

<%= link_to 'Back', shop_item_images_path %>

app/views/shop_item_images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Shop item:</strong>
  <%= @shop_item_image.shop_item_id %>
</p>

<p>
  <strong>Picture path:</strong>
  <%= @shop_item_image.picture_path %>
</p>

<%= link_to 'Edit', edit_shop_item_image_path(@shop_item_image) %> |
<%= link_to 'Back', shop_item_images_path %>